### ISSUE TITLE
Viewport does not resize on iOS when showing keyboard

### ISSUE THREAD

**Issue by bwindels** [element-hq/hydrogen-web#181]
So the room header becomes hidden

**Comment by jasikpark** [comment]
Could this not be fixed by using 100% height instead of 100vh? https://css-tricks.com/newsletter/232-scroll-story/

**Comment by bwindels** [comment]
Thanks for the pointer, would have to test if that fixes it. Another pointer: https://webreflection.github.io/screenfit/

**Comment by Johennes** [comment]
I believe `height: 100%` won't help here. Safari seems to be the only mobile browser that does _not_ resize the viewport when the keyboard shows. Instead the content is simply moved upwards and this seems to be intentional for performance reasons (see [webkit#141832](https://bugs.webkit.org/show_bug.cgi?id=141832)).

From what I'm grasping, the only practical way to deal with this is to use the `VisualViewport` API. That's only available on iOS 13 and above but that might be good enough?

I was able to get part of the way there by hacking around with something like this:

```
if (window.visualViewport) {
    function resizeHandler() {
        for (const sessionView of document.getElementsByClassName('SessionView')) {
            sessionView.style.height = window.visualViewport.height.toString() + 'px';
            document.getElementsByTagName('html')[0].style.height = window.visualViewport.height.toString() + 'px';
        }
    }

    window.visualViewport.addEventListener('resize', resizeHandler);
}
```

The initial scroll position of the `MessageComposer` element is still screwed up after opening the keyboard so this would need further fixing.
