### ISSUE TITLE
Redacting a reaction on an already redacted event makes sync blow up

### ISSUE THREAD

**Issue by ptman** [element-hq/hydrogen-web#483]
**Describe the bug**
Error is: Sync failed because of TypeError: target.annotations is undefined
I get the on the top on green background. I can share logs privately.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 91.0.2
 - Hydrogen 0.2.8 (and 0.2.5 had the same problem)

**Comment by bwindels** [comment]
Notes from having looked at ptman's logs:

so first the message ($1his...) is redacted
then the reaction to that message ($VRF...)
and it sees that $VRF was a reaction and tries to recalculate the remaining reactions on the target of the reaction ($1his ...) and that fails because the reactions there have already been removed during the prior redaction
